config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @post.comments.create(params[:comment].permit(:name,:email,:message))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @post.comments.find(params[:id]).destroy
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :fetch_post, only: [:show,:edit,:update,:destroy]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def fetch_post()
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>

  <div class="col-md-12">
    <h4>Leave a comment</h4>
    <div class="row">
      <div class="col-md-6">
        <%= f.input :name %>
      </div>
      <div class="col-md-6">
        <%= f.input :email %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <%= f.input :message %>
      </div>
      <div class="col-md-12 text-right">
        <%= f.button :submit, class: "btn-primary" %>
      </div>
    </div>
  </div>

<%end%>

app/views/comments/_post_comments.html.erb
<% @post.comments.each do |comment|%>
  <% if comment.name != nil %>
    <div class="card" style="margin-top: 10px; padding: 10px 0 5px 10px">
      <div class="row">
        <div class="col-md-10">
          <p><strong><%=comment.name%></strong>: <%= comment.message%></p>
        </div>
        <div class="col-md-2 text-center">
          <%= link_to "Delete", [comment.post, comment], method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
        </div>
      </div>
    </div>
  <%end%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Simple Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/posts/new">Create Post</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="jumbotron text-center">
      <h1 class="display-4"><%= yield :page_title%></h1>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<% content_for :page_title, "Edit Post"%>
<div class="container">
  <%= simple_form_for @post do |f| %>
    <div class="col-md-12">
      <%= f.input :title %>
    </div>
    <div class="col-md-12">
      <%= f.input :content %>
    </div>
    <div class="col-md-12 text-right">
      <%= f.button :submit, class: "btn-primary" %>
    </div>
  <%end%>
</div>

app/views/posts/index.html.erb
<% content_for :page_title, "All Posts"%>
<div class="container" style="margin-top:20px">
  <% @posts.each do |post|%>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title text-danger"><%= link_to post.title, post %></h4>
        <p class="card-text"><%= truncate(post.content, :length => 300, :omission => '... (continued)') %></p>
      </div>
    </div><br>
  <%end%>
</div>

app/views/posts/new.html.erb
<% content_for :page_title, "Create New Post"%>
<div class="container">
  <%= simple_form_for @post do |f| %>
    <div class="col-md-12">
      <%= f.input :title %>
    </div>
    <div class="col-md-12">
      <%= f.input :content %>
    </div>
    <div class="col-md-12 text-right">
      <%= f.button :submit, class: "btn-primary" %>
    </div>
  <%end%>
</div>

app/views/posts/show.html.erb
<%content_for :page_title, @post.title%>


<div class="container">
  <div class="col-md-12" style="margin-top: 35px">
    <div class="row">
      <div class="col-md-10">
        <p><%= @post.content %></p>
      </div>
      <div class="col-md-2 text-center">
        <b><h4>Actions</h4></b>
        <div class="col-md-12 text-center">
          <%= link_to "Edit", edit_post_path(@post), class: "btn btn-info btn-sm" %>
          <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
        </div>
      </div>
    </div>

    <br><br>
  </div>
  <div class="col-md-12">
    <h5><strong><%= @post.comments.count %></strong> comments</h5>
    <hr>
  </div>

  <%=render 'comments/comment_form'%>
  <hr>
  <%=render 'comments/post_comments'%>

  <br><br><br>

</div>